/**
 * List of majors offered in UCSD/ need to extract from API endpoints in the future for other schools
 */
export const majors = [
  '5-year International Studies—Economics BA/MIA',
  '5-year International Studies—International Business BA/MIA',
  '5-year International Studies—Political Science BA/MIA',
  'Aerospace Engineering BS',
  'Anthropological (Archaeology) BA',
  'Anthropology (Biological Anthropology) BA',
  'Anthropology (Climate Change and Human Solutions) BA',
  'Anthropology (Sociocultural Anthropology) BA',
  'Biochemistry/Chemistry BS',
  'Bioengineering: Bioinformatics BS',
  'Bioengineering: BioSystems BS',
  'Bioengineering: Biotechnology BS',
  'Bioengineering BS',
  'Bioinformatics BS',
  'Biological Anthropology BS',
  'Biology with a Specialization in Bioinformatics BS',
  'Business Psychology BS',
  'Chemical Engineering BS',
  'Chemistry BS',
  'Chemistry with Specialization in Earth Sciences BS',
  'Chinese Studies BA',
  'Classical Studies BA',
  'Cognitive and Behavioral Neuroscience Bachelor of Science BS',
  'Cognitive and Behavioral Neuroscience BS',
  'Cognitive Science BA/BS',
  'Cognitive Science with Specialization in Clinical Aspects of Cognition BS',
  'Cognitive Science with Specialization in Design and Interaction BS',
  'Cognitive Science with Specialization in Language and Culture BS',
  'Cognitive Science with Specialization in Machine Learning and Neural Computation BS',
  'Cognitive Science with Specialization in Neuroscience BS',
  'College Special Individual Majors BA',
  'Communication BA',
  'Computer Engineering BS',
  'Computer Science BA/BS',
  'Computer Science with Specialization in Bioinformatics BS',
  'Critical Gender Studies BA',
  'Dance BA',
  'Data Science BS',
  'Earth Sciences BS',
  'Ecology, Behavior, and Evolution BS',
  'Economics BA',
  'Economics–Public Policy BA/MPP only',
  'Education Sciences BS',
  'Electrical Engineering and Society BA',
  'Electrical Engineering BS',
  'Engineering Physics BS',
  'Environmental Chemistry BS',
  'Environmental Engineering BS',
  'Environmental Systems—Earth Sciences BS',
  'Environmental Systems—Ecology, Behavior and Evolution BS',
  'Environmental Systems—Environmental Chemistry BS',
  'Environmental Systems—Environmental Policy BA',
  'Ethnic Studies BA',
  'General Biology BS',
  'General Physics BA',
  'General Physics/Secondary Education BA',
  'German Studies BA',
  'Global Health BA',
  'Global Health BS',
  'Global South Studies BA',
  'History BA',
  'Human Biology BS',
  'Human Developmental Sciences BA',
  'Human Developmental Sciences BS',
  'Human Developmental Sciences with a Specialization in Equity and Diversity BS',
  'Human Developmental Sciences with a Specialization in Healthy Aging BS',
  'Interdisciplinary Computing and the Arts BA',
  'International Studies—Anthropology BA',
  'International Studies—Economics BA',
  'International Studies—History BA',
  'International Studies—International Business BA',
  'International Studies—Linguistics BA',
  'International Studies—Literature BA',
  'International Studies—Philosophy BA',
  'International Studies—Political Science BA',
  'International Studies—Sociology BA',
  'Italian Studies BA',
  'Japanese Studies BA',
  'Jewish Studies BA',
  'Joint Economics-Mathematics BS',
  'Joint Mathematics-Economics BS',
  'Language Studies BA',
  'Latin American Studies BA',
  'Latin American Studies with a Concentration in Mexico BA',
  'Latin American Studies with a Concentration in Migration and Border Studies BA',
  'Linguistics (Cognition and Language) BA',
  'Linguistics (Language and Society) BA',
  'Linguistics (Speech and Language Sciences) BA',
  'Linguistics BA',
  'Literature/Writing BA',
  'Literatures in English BA',
  'Literatures in Spanish BA',
  'Management Science BS',
  'Marine Biology BS',
  'Mathematics (Applied) BS',
  'Mathematics BS',
  'Mathematics—Applied Science BS',
  'Mathematics—Computer Science BS',
  'Mathematics—Scientific Computation BS',
  'Mathematics—Secondary Education BA',
  'Mechanical Engineering BS',
  'Mechanical Engineering with a Specialization in Controls and Robotics BS',
  'Mechanical Engineering with a Specialization in Fluid Mechanics and Thermal Systems BS',
  'Mechanical Engineering with a Specialization in Materials Science and Engineering BS',
  'Mechanical Engineering with a Specialization in Mechanics of Materials BS',
  'Mechanical Engineering with a Specialization in Renewable Energy and Environmental Flows BS',
  'Microbiology BS',
  'Molecular and Cell Biology BS',
  'Molecular Synthesis BS',
  'Music BA',
  'Music/Humanities BA',
  'Nanoengineering BS',
  'Neurobiology BS',
  'Oceanic and Atmospheric Sciences BS',
  'Pharmacological Chemistry BS',
  'Philosophy BA',
  'Physics BS',
  'Physics/Biophysics BS',
  'Physics with Specialization in Astrophysics BS',
  'Physics with Specialization in Computational Physics BS',
  'Physics with Specialization in Earth Sciences BS',
  'Physics with Specialization in Materials Physics BS',
  'Political Science (American Politics) BA',
  'Political Science (Comparative Politics) BA',
  'Political Science (International Affairs) BA/MIA only',
  'Political Science (International Relations) BA',
  'Political Science (Political Theory) BA',
  'Political Science (Public Law) BA',
  'Political Science (Public Policy) BA',
  'Political Science BA',
  'Probability and Statistics BS',
  'Psychology BA',
  'Psychology Bachelor of Science with a Specialization in Clinical Psychology BS',
  'Psychology Bachelor of Science with a Specialization in Cognitive Psychology BS',
  'Psychology Bachelor of Science with a Specialization in Developmental Psychology BS',
  'Psychology Bachelor of Science with a Specialization in Human Health BS',
  'Psychology Bachelor of Science with a Specialization in Sensation and Perception BS',
  'Psychology Bachelor of Science with a Specialization in Social Psychology BS',
  'Psychology BS',
  'Public Health BS',
  'Real Estate and Development BS',
  'Russian, East European, and Eurasian Studies BA',
  'Sociology BA',
  'Sociology—American Studies BA',
  'Sociology—Culture and Communication BA',
  'Sociology—Economy and Society BA',
  'Sociology—International Studies BA',
  'Sociology—Law and Society BA',
  'Sociology—Science and Medicine BA',
  'Sociology—Social Inequity BA',
  'Speculative Design BA',
  'Structural Engineering BS',
  'Study of Religion BA',
  'Theatre BA',
  'Urban Studies and Planning BA',
  'Visual Arts (Art History/Criticism) BA',
  'Visual Arts (Media) BA',
  'Visual Arts (Studio) BA',
  'World Literature and Culture BA',
];
